import type { Transaction } from '../types';

export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: 1,
    dir: 'in',
    amount: 3200,
    category: 'Income',
    title: 'Paycheck · Acme Co',
    who: 'Acme Co',
    why: 'Payday',
    date: '2026-06-01',
    method: 'Direct deposit',
  },
  {
    id: 2,
    dir: 'out',
    amount: 1500,
    category: 'Necessity',
    title: 'Rent',
    who: 'Landlord',
    why: 'Monthly rent',
    date: '2026-06-01',
    method: 'Autopay',
  },
  {
    id: 3,
    dir: 'out',
    amount: 800,
    category: 'Investing',
    title: 'Brokerage transfer',
    who: 'Fidelity',
    why: 'Monthly investing',
    date: '2026-06-02',
    method: 'Transfer',
  },
  {
    id: 4,
    dir: 'out',
    amount: 120,
    category: 'Necessity',
    title: 'Groceries',
    who: 'Whole Foods',
    why: 'Weekly groceries',
    date: '2026-06-06',
    method: 'Card',
  },
  {
    id: 5,
    dir: 'in',
    amount: 50,
    category: 'Repayment',
    title: 'Venmo · Sam',
    who: 'Sam',
    why: 'Dinner split',
    date: '2026-06-08',
    method: 'Venmo',
  },
  {
    id: 6,
    dir: 'out',
    amount: 200,
    category: 'Sent to people',
    title: 'Sent to Mom',
    who: 'Mom',
    why: 'Birthday gift',
    date: '2026-06-12',
    method: 'Zelle',
  },
  {
    id: 7,
    dir: 'out',
    amount: 90,
    category: 'Fun',
    title: 'Concert tickets',
    who: 'Ticketmaster',
    why: 'Show with Sam',
    date: '2026-06-14',
    method: 'Card',
  },
];
